-- Historicamente este archivo desactivaba RLS en actor_profiles y daba grant
-- all a anon/authenticated. Eso quedo cerrado: ver supabase/harden-access.sql,
-- que activa RLS en actor_profiles igual que en el resto de tablas.
-- Si al sembrar datos (seed) aparece un error de "row-level security", es
-- porque el script esta usando SUPABASE_ANON_KEY en vez de
-- SUPABASE_SERVICE_ROLE_KEY. Revisa .env.local, no reabras RLS.
