-- Historicamente este archivo daba "grant all" a anon/authenticated (v1: no RLS,
-- single-analyst tool). Eso quedo cerrado: ver supabase/harden-access.sql.
-- No hace falta correr nada de aqui para una instalacion nueva, RLS ya viene
-- activado en schema.sql y sin policies, asi que anon/authenticated no tienen
-- acceso por defecto. Este archivo se deja solo para referencia historica.
